### ISSUE TITLE
The DSNet is not considered yet

### ISSUE THREAD

**Issue by mmsheybani** [gjy3035/Awesome-Crowd-Counting#111]
Please check DSNet and add it to your review.
Its result is good...

Dai, F., Liu, H., Ma, Y., Cao, J., Zhao, Q., & Zhang, Y. (2019). Dense scale network for crowd counting. arXiv preprint arXiv:1906.09707.

Thanks

**Comment by zengxin1020** [comment]
@mmsheybani Thanks. We updated it not long age.
[DSNet] Dense Scale Network for Crowd Counting (ICMR 2021)
