### ISSUE TITLE
论文链接指向错误

### ISSUE THREAD

**Issue by Hibari36** [gjy3035/Awesome-Crowd-Counting#129]
Journal 2022中
论文[GNA] Video Crowd Localization with Multi-focus Gaussian Neighborhood Attention and a Large-Scale Benchmark (TMM) [[paper](https://ieeexplore.ieee.org/document/9875106)][[code](https://github.com/HopLee6/VSCrowd-Dataset)]中的[paper]链接错误指向了
[FIDTM] Focal Inverse Distance Transform Maps for Crowd Localization (TMM)[[paper](https://ieeexplore.ieee.org/document/9875106)] [[code](https://github.com/dk-liang/FIDTM)]GitHub stars [[project](https://dk-liang.github.io/FIDTM/)]
希望修改

**Comment by zengxin1020** [comment]
@Hibari36 Thanks!
