### ISSUE TITLE
How to convert density map to actual count number?

### ISSUE THREAD

**Issue by Metal-joker** [gjy3035/Awesome-Crowd-Counting#18]
Very confused

**Comment by gjy3035** [comment]
The sum of all pixel values in density map.

**Comment by sa171** [comment]
How is the sum of pixels representing total count?

**Comment by gjy3035** [comment]
@sa171 Please refer to the process of density map generation: 
http://papers.nips.cc/paper/4043-learning-to-count-objects-in-images.pdf
http://openaccess.thecvf.com/content_cvpr_2016/papers/Zhang_Single-Image_Crowd_Counting_CVPR_2016_paper.pdf

**Comment by Metal-joker** [comment]
@sa171 From my perspective, each guassian kernel represent a person and each guassian kernel's pixel value should sum to 1, so the sum of each pixel values will be the total count of person.

@gjy3035 Thanks a lot.

**Comment by sa171** [comment]
@Metal-joker thanks i get it a little, so are they distributing pixel values such that if in a region the sum is 1 then it indicates 1 head?

**Comment by sa171** [comment]
@giy3035 thanks for that but they are using the density kernel for generation of ground truth density map so I'm not getting how the count is obtained from the estimated density map.

**Comment by Metal-joker** [comment]
@sa171 Most datasets use a dot as annotation for a head, but for learning, a dot can't provide enough information, as referred to this paper: http://papers.nips.cc/paper/4043-learning-to-count-objects-in-images.pdf. So they decide to use the normalized guassian kernel to represent a person, which the sum of value equal to 1. So, in my view, estimated density map still a set of guassian kernels and the sum of all pixel value is equal to the number of guassian kernels, that is, the total count of people.

**Comment by sa171** [comment]
Thanks

**Comment by gjy3035** [comment]
Thanks for @Metal-joker 's reply!
