### ISSUE TITLE
C^3 Framework Link is death

### ISSUE THREAD

**Issue by Pipoderoso** [gjy3035/Awesome-Crowd-Counting#20]

**Comment by kunli-cs** [comment]
Maybe the author doesn't want to release the code now.

**Comment by kunli-cs** [comment]
> _No description provided._

Maybe the author doesn't want to release the code now.

**Comment by gjy3035** [comment]
@Pipoderoso @kunli-cs Thanks for your attention!
We had set the C^3 as a private repo. 
Considering that the incomplete code may mislead the other researchers, the code will be released until we finish it. Meanwhile, we are training some popular methods and baselines on the mainstream datasets (the results will be shown in the repo). The experiments will also take a lot of time.

If everything goes well, the code will be released in March, 2019.

**Comment by kunli-cs** [comment]
@gjy3035 Thanks.

**Comment by gjy3035** [comment]
The link is alive.
