### ISSUE TITLE
Reult of SANet maybe better.

### ISSUE THREAD

**Issue by LaiPiXiong** [gjy3035/Awesome-Crowd-Counting#3]
Hi, I found that the results show in SANet is partially better the the methods in your table. SANet is from 2018 eccv.

**Comment by gjy3035** [comment]
@LaiPiXiong Thanks for your attention!
In fact, some papers have performed the methods listed in the table of this repo. Unforetunately, I am very busy becuase many ddls. I will update the table ASAP. 
And, if you are interested in the repo, welcome you to pull requests.
Thanks a lot!

**Comment by LaiPiXiong** [comment]
That's really kind of you. This repo help me a lot to learn crowd count.
