### ISSUE TITLE
Do you recovery ASDNET? Is the size of input image is (224 X 224)?

### ISSUE THREAD

**Issue by LaiPiXiong** [gjy3035/Awesome-Crowd-Counting#31]
I try to recovery ASDNet, but I cannot find the size of input image. Do you recovery it?

**Comment by gjy3035** [comment]
I don't read this paper. After submission of my paper (mid-March), I maybe read it then discuss it  with you. 
You can also send email to the authors to request the source code.

**Comment by LaiPiXiong** [comment]
Thanks very much! Actually, we have recovery it last week

**Comment by gjy3035** [comment]
@LaiPiXiong Good Job!
