### ISSUE TITLE
How to visualize the density map from the h5 files?

### ISSUE THREAD

**Issue by tangjilin** [gjy3035/Awesome-Crowd-Counting#32]
How to visualize the density map from the h5 files?
Now I do it by:

from matplotlib import cm
plt.imshow(output , cmap = cm.jet )

However I feel my  effect is not good as the result in the paper. It looks not very clear.

Am I wrong? Can you tell me how to realize it? Thanks!

**Comment by gjy3035** [comment]
Your visualization operation is correct. 
You should check the generation for density map (kernel size and stride) is same as the paper.
