### ISSUE TITLE
UCF CC 50 link is death 

### ISSUE THREAD

**Issue by Pipoderoso** [gjy3035/Awesome-Crowd-Counting#41]
It seems like UCF change their website and took down the UCF CC dataset. Do you have any direct link?

**Comment by kunli-cs** [comment]
You can download the UCF_QNRF dataset from this [link](https://drive.google.com/open?id=1fLZdOsOXlv2muNB_bXEW6t-IS9MRziL6)

**Comment by Pipoderoso** [comment]
Thanks for the quick answer!
