### ISSUE TITLE
Try to reproduce <<Context-aware crowd counting>>

### ISSUE THREAD

**Issue by CommissarMa** [gjy3035/Awesome-Crowd-Counting#59]
I am trying to reproduce "Context-aware crowd counting"(CVPR2019), but get mae=69.02 in ShTechA which is wrose than 62.3 in paper.  My code is https://github.com/CommissarMa/Context-Aware_Crowd_Counting-pytorch.

**Comment by CommissarMa** [comment]
I have achieved the 62.3 MAE in ShanghaiTechA. The code is released at https://github.com/CommissarMa/Context-Aware_Crowd_Counting-pytorch

**Comment by gjy3035** [comment]
Great work!  I will add your code link to this repo!

**Comment by gjy3035** [comment]
@wwwzxoe303com Please add this link. Thanks a lot!

**Comment by wwwzxoe303com** [comment]
@CommissarMa Thank you for sharing the code.
