### ISSUE TITLE
Maybe 'Switch-CNN' deserves some attention

### ISSUE THREAD

**Issue by LaiPiXiong** [gjy3035/Awesome-Crowd-Counting#6]
2017-CVPR-'Switch-CNN' has better performance than most of 2018 results. Though it is a improvement of 'MCNN', but in my opinion, 'Switch-CNN' maybe the method witch use multi-CNN correctly.

**Comment by ntvy95** [comment]
If my performance summarization has no mistakes then the answer is: Not really. Here is a look at it. I will try to convert my performance to GitHub page and make a pull request when I get some free time (hopefully the next week).

Capture link: https://ibb.co/cCgD1L

Hope this helps.

**Comment by gjy3035** [comment]
@ntvy95 Thanks!
It's amazing summary!

**Comment by LaiPiXiong** [comment]
Yes, you are right. And thanks very much for your contribution!@ntvy95

**Comment by gjy3035** [comment]
Hi, @ntvy95 , your leaderboard is  very awesome! 
Now, I have free time to maintain it. If yes, you can share the unfinished work with me. We will update it and add it in the repo ASAP.

**Comment by gjy3035** [comment]
@ntvy95 Thanks a lot! This is really a powerful table. 
For a better maintainability of this repo,  I think I need to find a brief way to list them. 
Anyway, I will complete the update as soon as possible.
