### ISSUE TITLE
404 for CVPR2019 link 

### ISSUE THREAD

**Issue by ttpro1995** [gjy3035/Awesome-Crowd-Counting#61]
Link to CVPR2019 paper is 404 

- Recurrent Attentive Zooming for Joint Crowd Counting and Precise Localization (CVPR2019) [paper]
- Density Map Regression Guided Detection Network for RGB-D Crowd Counting and Localization (CVPR2019) [paper]
- Residual Regression with Semantic Prior for Crowd Counting (CVPR2019) [paper]
Wide-Area Crowd Counting via Ground-Plane Density Maps and Multi-View Fusion CNNs (CVPR2019) [paper]
- Leveraging Heterogeneous Auxiliary Tasks to Assist Crowd Counting (CVPR2019) [paper]

**Comment by gjy3035** [comment]
[CVF’s website](http://openaccess.thecvf.com/CVPR2019.py) only provides the list of the accepted papers now. I think these links will work soon.
