### ISSUE TITLE
Pytorch implementation (notebook) of SPN on Kaggle

### ISSUE THREAD

**Issue by ttpro1995** [gjy3035/Awesome-Crowd-Counting#66]
I make [SPN](https://www.kaggle.com/tthien/spn-scale-pyramid-network-for-crowd-counting) implementation on Kaggle.

Here is full experiment notebook with [ShanghaiTech dataset 
](https://www.kaggle.com/tthien/shanghaitech-with-people-density-map)
 that can be fork and run: 
https://www.kaggle.com/tthien/spn-scale-pyramid-network-for-crowd-counti

**Comment by ttpro1995** [comment]
MAE on ShanghaiTech part A (test set) is 36.988. Much better than on paper. I wonder if there is mistake in my code. Could anyone check for bug ?

**Comment by cxm1995** [comment]
DATA_PATH = "../input/shanghaitech_with_people_density_map/ShanghaiTech/part_B/train_data/"
TEST_DATA_PATH = "../input/shanghaitech_with_people_density_map/ShanghaiTech/part_B/test_data/"
I think you are testing part_B ?

**Comment by ttpro1995** [comment]
uh, I see. 
Thank
