### ISSUE TITLE
Some results on MALL 

### ISSUE THREAD

**Issue by LaiPiXiong** [gjy3035/Awesome-Crowd-Counting#67]
| MAE | MSE
-- | -- | --
2019-PRL DigCrowd | 3.21 | 16.4
2018-CVPR DecideNet | 1.52 | 1.90
2019-Axive MAN | 1.76 | 2.2
2019-WACV SAAN | 1.28 | 1.68
2018-IJCAI RSAN | 1.72 | 2.1

**Comment by LaiPiXiong** [comment]
2019-PRL Depth Information Guided Crowd Counting for Complex Crowd Scenes
2018-CVPR DecideNet
2019-Axive Mask-aware networks for crowd counting
2019-WACV  Crowd Counting Using Scale-Aware Attention Networks
2018 IJCAI Crowd Counting using Deep Recurrent Spatial-Aware Network

**Comment by wwwzxoe303com** [comment]
@LaiPiXiong Thanks!
