### ISSUE TITLE
competitions about crowd counting

### ISSUE THREAD

**Issue by yuzehui1996** [gjy3035/Awesome-Crowd-Counting#68]
Have you ever heard about the  the crowd counting competitions? If so, thanks for your suggestions!

**Comment by angelOfMoon** [comment]
https://biendata.com/competition/cloudcup2018/

**Comment by gjy3035** [comment]
https://aistudio.baidu.com/aistudio/competition/detail/6

**Comment by yuzehui1996** [comment]
Thanks a lot!
