### ISSUE TITLE
关于制作 Ground-truth

### ISSUE THREAD

**Issue by duanyinong** [gjy3035/Awesome-Crowd-Counting#7]
您好，首先非常感谢您的工作。
我想请问您发布的制作Ground-truth的代码是几核适应高斯核的代码吗？

**Comment by LaiPiXiong** [comment]
他发布的代码，应该是论文给的链接里面的。至于是否是几何适应性的可以依据论文查看一下

**Comment by vlad3996** [comment]
You can try to generate maps with [this code](https://github.com/vlad3996/computing-density-maps), if you want. 
You can choose how to compute sigma : distance to 3 nearest neighbors, distance to nearest neighbor, or fixed value. Optionally clip sigma if it is lower than threshold. 
I've used pre-computed gaussian kernels and fast neighbors search to speed up density maps creation.

**Comment by gjy3035** [comment]
@vlad3996 Thanks for your pre-processing code! I will add to the repo ASAP.

**Comment by gjy3035** [comment]
I have added the fast generation code into the repo. So I close this issue. 
Thanks for your attention! @duanyinong @LaiPiXiong @vlad3996
