### ISSUE TITLE
404 for JHU-CROWD Dataset link

### ISSUE THREAD

**Issue by Tzclxy** [gjy3035/Awesome-Crowd-Counting#82]
The link to JHU-CROWD Dataset seems to be 404.

**Comment by gjy3035** [comment]
this dataset is not released. please contact the authors of the paper.
https://engineering.jhu.edu/vpatel36/wp-content/uploads/2019/10/crowd_dataset_v2_cam_v3.pdf

**Comment by Tzclxy** [comment]
OK. Thanks for the quick answer.
